import { images } from './assets/index';

const data = [
  {
    title: 'Model 3',
    desc: 'Order Online for Touchless Delivery',
    descLink: '',
    backgroundImg: images.Model3,
    leftBtnTxt: 'Custom Order',
    leftBtnLink: '',
    rightBtnTxt: 'Existing Invertory',
    rightBtnLink: '',
    twoButtons: true,
    first: true,
  },
  {
    title: 'Model Y',
    desc: 'Order Online for Touchless Delivery',
    descLink: '',
    backgroundImg: images.ModelY,
    leftBtnTxt: 'Custom Order',
    leftBtnLink: '',
    rightBtnTxt: 'Existing Invertory',
    rightBtnLink: '',
    twoButtons: true,
    first: false,
  },
  {
    title: 'Model S',
    desc: 'Order Online for Touchless Delivery',
    descLink: '',
    backgroundImg: images.ModelS,
    leftBtnTxt: 'Custom Order',
    leftBtnLink: '',
    rightBtnTxt: 'Existing Invertory',
    rightBtnLink: '',
    twoButtons: true,
    first: false,
  },
  {
    title: 'Model X',
    desc: 'Order Online for Touchless Delivery',
    descLink: '',
    backgroundImg: images.ModelX,
    leftBtnTxt: 'Custom Order',
    leftBtnLink: '',
    rightBtnTxt: 'Existing Invertory',
    rightBtnLink: '',
    twoButtons: true,
    first: false,
  },
  {
    title: 'Solar Panels',
    desc: 'Lowest Cost Solar Panels in America',
    descLink: '',
    backgroundImg: images.SolarPanels,
    leftBtnTxt: 'Order Now',
    leftBtnLink: '',
    rightBtnTxt: 'Learn More',
    rightBtnLink: '',
    twoButtons: true,
    first: false,
  },
  {
    title: 'Solar Roof',
    desc: 'Produce Clean Energy From Your Roof',
    descLink: '',
    backgroundImg: images.SolarRoof,
    leftBtnTxt: 'Order Now',
    leftBtnLink: '',
    rightBtnTxt: 'Learn More',
    rightBtnLink: '',
    twoButtons: true,
    first: false,
  },
  {
    title: 'Accessories',
    desc: '',
    descLink: '',
    backgroundImg: images.Accessories,
    leftBtnTxt: 'Shop Now',
    leftBtnLink: '',
    twoButtons: false,
    first: false,
  },
];

export default data;
